### ISSUE TITLE
complex number tests generate zero solution with PETSc 3.12 (ubuntu focal 20.04 PPA build)

### ISSUE THREAD

**Issue by drew-parsons** [FEniCS/dolfinx#1612]
A problem was reported at https://fenicsproject.discourse.group/t/helmholtz-complex-xdmf-contains-zeros-only/6204 for dolfinx 0.1.0 in complex number mode. The problem is with the PPA build for ubuntu focal 20.04. The helmholtz2D demo (demo_helmholtz_2d.py) generates a null solution (0 in both real and imaginary parts).  I can reproduce the null result on a fresh cloud installation of focal.

The "equivalent" build on Debian unstable does not have the problem: it generates a nontrivial periodically repeating solution for the helmholtz2D demo.

The PPA build log is https://launchpadlibrarian.net/546658626/buildlog_ubuntu-focal-amd64.fenics-dolfinx_1%3A0.1.0-2~ppa1~focal3_BUILDING.txt.gz
I haven't spotted any obvious problems there though.

focal provides PETSc 3.12 while my working system (Debian unstable+experimental) provides PETSc 3.15.  Do we know the circumstances in which dolfinx complex might appear to run successfully, but generate a trivial zero solution?  Are there any known problems with PETSc 3.12 that might explain the zero result?

**Comment by drew-parsons** [comment]
I can reproduce this error with a fresh build of PETSc 3.12 on Debian unstable (where PETSc 3.14 or 3.15 is otherwise used).

That supports the hypothesis that PETSc 3.12 is the problem here, so it should be possible to reproduce in docker builds using petsc 3.12.

Updating the title accordingly.

**Comment by francesco-ballarin** [comment]
@drew-parsons is this still happening with dolfinx 0.7.0 and PETSc 3.20?

**Comment by drew-parsons** [comment]
PETSc 3.12 fails on debian unstable:
```
/projects/petsc/build/3.12/petsc-3.12.4+dfsg1/src/mat/impls/hypre/mhypre.c: In function ‘MatCreateFromParCSR’:
/projects/petsc/build/3.12/petsc-3.12.4+dfsg1/src/mat/impls/hypre/mhypre.c:1506:43: error: assignment to expression with array type
 1506 |       hypre_ParCSRMatrixColStarts(parcsr) = (HYPRE_BigInt*)(map->range + myid);
      |                                           ^
/projects/petsc/build/3.12/petsc-3.12.4+dfsg1/src/mat/impls/hypre/mhypre.c:1513:43: error: assignment to expression with array type
 1513 |       hypre_ParCSRMatrixRowStarts(parcsr) = (HYPRE_BigInt*)(map->range + myid);
      |                                           ^
gmake[4]: *** [gmakefile:156: x86_64-linux-gnu-real-debug/obj/mat/impls/hypre/mhypre.o] Error 1
```

ubuntu focal 20.04: has PETSc 3.12 but does not have the tools to build basix 0.7.0.  In particular infrastructure for pyproject.toml (pybuild-plugin-pyproject) is missing.

Either way deeper hacking would be needed to test.  I'd just say dolfinx is incompatible with PETSc 3.12 and close this bug with a higher minimum  PETSc version.  In fact cpp/CMakeLists.txt already demands PETSc>=3.15 so the job's done.

**Comment by drew-parsons** [comment]
https://github.com/FEniCS/dolfinx/blob/29a86c4d845d1ff4ae224209f91f067f52684796/cpp/CMakeLists.txt#L208

Closed by #1927
